sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.1.4

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_install:
- # sudo pip install python-coveralls
- npm install --save-dev coveralls
- git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
- sudo apt-get -y install perl
- chmod +x .scripts/InstallExiftool.sh && sudo ./.scripts/InstallExiftool.sh 
- 'echo "EXIFTOOL: $(exiftool -ver)"'

script:
- dotnet restore
- dotnet msbuild /p:configuration=Release 
- chmod +x .scripts/TestCoverage.sh && ./.scripts/TestCoverage.sh 

cache:
  directories:
    - $HOME/.nuget/packages