sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.1.4

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_install:
- git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
- sudo apt-get -y install perl
- sudo apt-get -y install coveralls
- coveralls --version
- chmod +x .scripts/InstallExiftool.sh
- sudo ./.scripts/InstallExiftool.sh 
- 'echo "EXIFTOOL: $(exiftool -ver)"'

script:
- dotnet restore
- dotnet msbuild /p:configuration=Release 
- ./src/packages/coveralls.io/1.4.2/tools/coveralls.net.exe --version
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/Core.Test/Core.Test.csproj
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/ExifToolWrapper.Test/ExifToolWrapper.Test.csproj
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/FileImporter.Test/FileImporter.Test.csproj
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/LuceneNet.Test/LuceneNet.Test.csproj
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/Picasa.Test/Picasa.Test.csproj
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:configuration=Release tests/NetMq.Test/NetMq.Test.csproj

cache:
  directories:
    - $HOME/.nuget/packages