image:
  - Visual Studio 2017
#  - Ubuntu

configuration: Release	
#platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_NuGetVersion%'
  package_version: '%GitVersion_NuGetVersion%'
  #version: '{version}'
  #package_version: '{version}'
  # assembly_version: '{version}'
  # file_version: '{version}'
  informational_version: '%GitVersion_InformationalVersion%'

install:
- cmd: >-
    choco install gitversion.portable -pre -y

    choco install opencover.portable

    REM choco install dotcover -y

    choco install codecov -y

    powershell .\.scripts\InstallExiftool.ps1

    C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver

    git submodule update --init --recursive
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    # .scripts\TestCoverage.DotCover.ps1

    .scripts\TestCoverage.ps1

    codecov -f coverage-dotnet.xml